# Generated by Django 2.0.7 on 2020-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('location', models.CharField(default='POINT(0 0)', max_length=200)),
                ('state', models.CharField(default='por validar', max_length=200)),
                ('category', models.CharField(default='CONSTRUCTION', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('upd_date', models.DateTimeField(verbose_name='date upated')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceCategory',
            fields=[
                ('category', models.CharField(default='', max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceState',
            fields=[
                ('state', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
