# Generated by Django 2.0.7 on 2020-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('address', models.CharField(max_length=600)),
                ('location', models.CharField(default='POINT(0 0)', max_length=200)),
                ('state', models.CharField(choices=[('por validar', 'por validar'), ('validado', 'validado'), ('Resolvido', 'Resolvido')], max_length=50)),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'CONSTRUCTION'), ('SPECIAL_EVENT', 'SPECIAL_EVENT'), ('INCIDENT', 'INCIDENT'), ('WEATHER_CONDITION', 'WEATHER_CONDITION'), ('ROAD_CONDITION', 'ROAD_CONDITION')], max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('upd_date', models.DateTimeField(verbose_name='date upated')),
            ],
        ),
    ]
